# Dockerfile para el microservicio de  Notifications
FROM node:18

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar los archivos de definición de dependencias
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de los archivos de la aplicación
COPY . .

# Exponer el puerto en el que la aplicación escucha
EXPOSE 3004

# Comando para iniciar la aplicación
CMD ["npm", "run", "start:prod"]
